//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASVURULAR
    {
        public BASVURULAR()
        {
            this.Makale = new HashSet<Makale>();
        }
    
        public int BASVURUID { get; set; }
        public string isim { get; set; }
        public string email { get; set; }
        public byte[] Resim { get; set; }
        public string sifre { get; set; }
        public string üniversite { get; set; }
        public string bölüm { get; set; }
        public string sınıf { get; set; }
        public string cep { get; set; }
        public string cv { get; set; }
        public string mesaj { get; set; }
    
        public virtual ICollection<Makale> Makale { get; set; }
    }
}
