//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Basvuru : DbContext
    {
        public Basvuru()
            : base("name=Basvuru")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BASVURULAR> BASVURULAR { get; set; }
        public virtual DbSet<Galeri> Galeri { get; set; }
        public virtual DbSet<Makale> Makale { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<universite> universite { get; set; }
        public virtual DbSet<Yorum> Yorum { get; set; }
    }
}
