//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makale
    {
        public Makale()
        {
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int ID { get; set; }
        public string Icerik { get; set; }
        public System.DateTime YayımTarihi { get; set; }
        public int YazarID { get; set; }
        public Nullable<int> GaleriID { get; set; }
    
        public virtual BASVURULAR BASVURULAR { get; set; }
        public virtual Galeri Galeri { get; set; }
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
